var clover = new Object();

// JSON: {classes : [{name, id, sl, el,  methods : [{sl, el}, ...]}, ...]}
clover.pageData = {"classes":[{"el":34,"id":63630,"methods":[{"el":29,"sc":5,"sl":27},{"el":33,"sc":5,"sl":31}],"name":"JWTSignatureAlg","sl":21}]}

// JSON: {test_ID : {"methods": [ID1, ID2, ID3...], "name" : "testXXX() void"}, ...};
clover.testTargets = {"test_109":{"methods":[{"sl":31}],"name":"testSpecificUserJWTClaims","pass":true,"statements":[{"sl":32}]},"test_116":{"methods":[{"sl":27},{"sl":31}],"name":"testEnableJWTAndClaims","pass":true,"statements":[{"sl":28},{"sl":32}]},"test_118":{"methods":[{"sl":31}],"name":"testEnableJWTAndClaims","pass":true,"statements":[{"sl":32}]},"test_126":{"methods":[{"sl":31}],"name":"testEnableJWTAndClaims","pass":true,"statements":[{"sl":32}]},"test_139":{"methods":[{"sl":31}],"name":"testAPIAccessWhenJWTCachingEnabledTestCase","pass":true,"statements":[{"sl":32}]},"test_15":{"methods":[{"sl":27},{"sl":31}],"name":"testJWTTokenAPITestCase","pass":true,"statements":[{"sl":28},{"sl":32}]},"test_152":{"methods":[{"sl":31}],"name":"testSpecificUserJWTClaims","pass":true,"statements":[{"sl":32}]},"test_18":{"methods":[{"sl":31}],"name":"testAPIAccessWhenJWTCachingEnabledTestCase","pass":true,"statements":[{"sl":32}]},"test_19":{"methods":[{"sl":31}],"name":"testAPIAccessWhenJWTCachingEnabledTestCase","pass":true,"statements":[{"sl":32}]},"test_197":{"methods":[{"sl":31}],"name":"testJWTTokenAPITestCase","pass":true,"statements":[{"sl":32}]},"test_283":{"methods":[{"sl":31}],"name":"testSpecificUserJWTClaims","pass":true,"statements":[{"sl":32}]},"test_353":{"methods":[{"sl":31}],"name":"testAPIAccessWhenJWTCachingEnabledTestCase","pass":true,"statements":[{"sl":32}]},"test_6":{"methods":[{"sl":31}],"name":"testSpecificUserJWTClaims","pass":true,"statements":[{"sl":32}]},"test_65":{"methods":[{"sl":27},{"sl":31}],"name":"testEnableJWTAndClaims","pass":true,"statements":[{"sl":28},{"sl":32}]}}

// JSON: { lines : [{tests : [testid1, testid2, testid3, ...]}, ...]};
clover.srcFileLines = [[], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [65, 116, 15], [65, 116, 15], [], [], [283, 65, 18, 19, 6, 109, 126, 353, 116, 118, 197, 139, 152, 15], [283, 65, 18, 19, 6, 109, 126, 353, 116, 118, 197, 139, 152, 15], [], []]
